event_event:
    resource: "@EventBundle/Resources/config/routing/event.yml"
    
event_annotations:
    resource: "@EventBundle/Controller"
    type: annotation


event_homepage:
    path:     /hello/{firstName}/{count}
    defaults: { _controller: EventBundle:Default:index }
